-- hyprspaces-managed bindings
hl.unbind("SUPER + code:10")
hl.unbind("SUPER + code:11")
hl.unbind("SUPER + code:12")
hl.unbind("SUPER + code:13")
hl.unbind("SUPER + code:14")
hl.unbind("SUPER + code:15")
hl.unbind("SUPER + code:16")
hl.unbind("SUPER + code:17")
hl.unbind("SUPER + code:18")
hl.unbind("SUPER + code:19")
hl.unbind("SUPER + SHIFT + code:10")
hl.unbind("SUPER + SHIFT + code:11")
hl.unbind("SUPER + SHIFT + code:12")
hl.unbind("SUPER + SHIFT + code:13")
hl.unbind("SUPER + SHIFT + code:14")
hl.unbind("SUPER + SHIFT + code:15")
hl.unbind("SUPER + SHIFT + code:16")
hl.unbind("SUPER + SHIFT + code:17")
hl.unbind("SUPER + SHIFT + code:18")
hl.unbind("SUPER + SHIFT + code:19")
hl.unbind("SUPER + LEFT")
hl.unbind("SUPER + RIGHT")
hl.unbind("SUPER + UP")
hl.unbind("SUPER + DOWN")
hl.unbind("SUPER + SHIFT + LEFT")
hl.unbind("SUPER + SHIFT + RIGHT")
hl.unbind("SUPER + SHIFT + UP")
hl.unbind("SUPER + SHIFT + DOWN")
hl.unbind("SUPER + mouse_up")
hl.unbind("SUPER + mouse_down")

local function hyprspaces_dispatch(action, arg)
    return function()
        local namespace = hl.plugin and hl.plugin.hyprspaces
        local dispatch = namespace and namespace.dispatch
        if not dispatch then
            return false, "hl.plugin.hyprspaces.dispatch is not registered"
        end
        return dispatch(action, arg)
    end
end

hl.bind("SUPER + code:10", hyprspaces_dispatch("switch", "1"), { description = "Hyprspaces switch 1" })
hl.bind("SUPER + code:11", hyprspaces_dispatch("switch", "2"), { description = "Hyprspaces switch 2" })
hl.bind("SUPER + code:12", hyprspaces_dispatch("switch", "3"), { description = "Hyprspaces switch 3" })
hl.bind("SUPER + code:13", hyprspaces_dispatch("switch", "4"), { description = "Hyprspaces switch 4" })
hl.bind("SUPER + code:14", hyprspaces_dispatch("switch", "5"), { description = "Hyprspaces switch 5" })
hl.bind("SUPER + code:15", hyprspaces_dispatch("switch", "6"), { description = "Hyprspaces switch 6" })
hl.bind("SUPER + code:16", hyprspaces_dispatch("switch", "7"), { description = "Hyprspaces switch 7" })
hl.bind("SUPER + code:17", hyprspaces_dispatch("switch", "8"), { description = "Hyprspaces switch 8" })
hl.bind("SUPER + code:18", hyprspaces_dispatch("switch", "9"), { description = "Hyprspaces switch 9" })
hl.bind("SUPER + code:19", hyprspaces_dispatch("switch", "10"), { description = "Hyprspaces switch 10" })

hl.bind("SUPER + SHIFT + code:10", hyprspaces_dispatch("move-window", "1"), { description = "Hyprspaces move window 1" })
hl.bind("SUPER + SHIFT + code:11", hyprspaces_dispatch("move-window", "2"), { description = "Hyprspaces move window 2" })
hl.bind("SUPER + SHIFT + code:12", hyprspaces_dispatch("move-window", "3"), { description = "Hyprspaces move window 3" })
hl.bind("SUPER + SHIFT + code:13", hyprspaces_dispatch("move-window", "4"), { description = "Hyprspaces move window 4" })
hl.bind("SUPER + SHIFT + code:14", hyprspaces_dispatch("move-window", "5"), { description = "Hyprspaces move window 5" })
hl.bind("SUPER + SHIFT + code:15", hyprspaces_dispatch("move-window", "6"), { description = "Hyprspaces move window 6" })
hl.bind("SUPER + SHIFT + code:16", hyprspaces_dispatch("move-window", "7"), { description = "Hyprspaces move window 7" })
hl.bind("SUPER + SHIFT + code:17", hyprspaces_dispatch("move-window", "8"), { description = "Hyprspaces move window 8" })
hl.bind("SUPER + SHIFT + code:18", hyprspaces_dispatch("move-window", "9"), { description = "Hyprspaces move window 9" })
hl.bind("SUPER + SHIFT + code:19", hyprspaces_dispatch("move-window", "10"), { description = "Hyprspaces move window 10" })

hl.bind("SUPER + LEFT", hyprspaces_dispatch("movefocus", "l"), { description = "Hyprspaces move focus left" })
hl.bind("SUPER + RIGHT", hyprspaces_dispatch("movefocus", "r"), { description = "Hyprspaces move focus right" })
hl.bind("SUPER + UP", hyprspaces_dispatch("movefocus", "u"), { description = "Hyprspaces move focus up" })
hl.bind("SUPER + DOWN", hyprspaces_dispatch("movefocus", "d"), { description = "Hyprspaces move focus down" })

hl.bind("SUPER + SHIFT + LEFT", hyprspaces_dispatch("move-window", "l"), { description = "Hyprspaces move window left" })
hl.bind("SUPER + SHIFT + RIGHT", hyprspaces_dispatch("move-window", "r"), { description = "Hyprspaces move window right" })
hl.bind("SUPER + SHIFT + UP", hyprspaces_dispatch("move-window", "u"), { description = "Hyprspaces move window up" })
hl.bind("SUPER + SHIFT + DOWN", hyprspaces_dispatch("move-window", "d"), { description = "Hyprspaces move window down" })

hl.bind("SUPER + mouse_up", hyprspaces_dispatch("cycle", "prev"), { description = "Hyprspaces cycle prev" })
hl.bind("SUPER + mouse_down", hyprspaces_dispatch("cycle", "next"), { description = "Hyprspaces cycle next" })

-- hl.bind("SUPER + TAB", hyprspaces_dispatch("switch", "previous"), { description = "Hyprspaces switch previous" })
-- hl.bind("SUPER + CTRL + TAB", hyprspaces_dispatch("focus-side"), { description = "Hyprspaces focus side" })
-- hl.bind("SUPER + ALT + S", hyprspaces_dispatch("swap-sides"), { description = "Hyprspaces swap sides" })
-- hl.bind("SUPER + ALT + M", hyprspaces_dispatch("move-to-side"), { description = "Hyprspaces move to side" })
-- hl.bind("SUPER + S", hyprspaces_dispatch("toggle-special"), { description = "Hyprspaces toggle special" })
-- hl.bind("SUPER + CTRL + code:10", hyprspaces_dispatch("bring-window", "1"), { description = "Hyprspaces bring window from 1" })
