-- hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
-- hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("HYPRCURSOR_THEME", "Qogir-Dark")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
-- Keep in sync with HYPRCURSOR_SIZE and the gsettings cursor-size in autostart.lua.
hl.env("XCURSOR_SIZE", "24")
hl.env("GDK_SCALE", "2")
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("TERMINAL", "kitty")
hl.env("QT_STYLE_OVERRIDE", "kvantum")
